version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shared-net

networks:
  shared-net:
    external: true